build:
	cd ./cliente-frontend && ./mvnw spring-boot:build-image -DskipTests; \
	cd ../conta-service && ./mvnw spring-boot:build-image -DskipTests; \
	cd ../hotel-service && ./mvnw spring-boot:build-image -DskipTests; \
	cd ../naming-service && ./mvnw spring-boot:build-image -DskipTests;
	